create table if not exists tenant
(
    id           bigint generated by default as identity
        constraint キー_name
            primary key,
    name         text   not null,
    display_name text   not null,
    created_at   bigint not null,
    updated_at   bigint not null
);

create table if not exists visit_history
(
    player_id      text   not null,
    tenant_id      bigint not null,
    competition_id text   not null,
    created_at     bigint,
    updated_at     bigint
);