--初期化
truncate competition;
truncate player;
truncate player_score;

-- 

--competition
INSERT INTO public.competition SELECT * from sqlite1.competition;
INSERT INTO public.competition SELECT * from sqlite2.competition;
INSERT INTO public.competition SELECT * from sqlite3.competition;
INSERT INTO public.competition SELECT * from sqlite4.competition;
INSERT INTO public.competition SELECT * from sqlite5.competition;
INSERT INTO public.competition SELECT * from sqlite6.competition;
INSERT INTO public.competition SELECT * from sqlite7.competition;
INSERT INTO public.competition SELECT * from sqlite8.competition;
INSERT INTO public.competition SELECT * from sqlite9.competition;
INSERT INTO public.competition SELECT * from sqlite10.competition;
INSERT INTO public.competition SELECT * from sqlite11.competition;
INSERT INTO public.competition SELECT * from sqlite12.competition;
INSERT INTO public.competition SELECT * from sqlite13.competition;
INSERT INTO public.competition SELECT * from sqlite14.competition;
INSERT INTO public.competition SELECT * from sqlite15.competition;
INSERT INTO public.competition SELECT * from sqlite16.competition;
INSERT INTO public.competition SELECT * from sqlite17.competition;
INSERT INTO public.competition SELECT * from sqlite18.competition;
INSERT INTO public.competition SELECT * from sqlite19.competition;
INSERT INTO public.competition SELECT * from sqlite20.competition;
INSERT INTO public.competition SELECT * from sqlite21.competition;
INSERT INTO public.competition SELECT * from sqlite22.competition;
INSERT INTO public.competition SELECT * from sqlite23.competition;
INSERT INTO public.competition SELECT * from sqlite24.competition;
INSERT INTO public.competition SELECT * from sqlite25.competition;
INSERT INTO public.competition SELECT * from sqlite26.competition;
INSERT INTO public.competition SELECT * from sqlite27.competition;
INSERT INTO public.competition SELECT * from sqlite28.competition;
INSERT INTO public.competition SELECT * from sqlite29.competition;
INSERT INTO public.competition SELECT * from sqlite30.competition;
INSERT INTO public.competition SELECT * from sqlite31.competition;
INSERT INTO public.competition SELECT * from sqlite32.competition;
INSERT INTO public.competition SELECT * from sqlite33.competition;
INSERT INTO public.competition SELECT * from sqlite34.competition;
INSERT INTO public.competition SELECT * from sqlite35.competition;
INSERT INTO public.competition SELECT * from sqlite36.competition;
INSERT INTO public.competition SELECT * from sqlite37.competition;
INSERT INTO public.competition SELECT * from sqlite38.competition;
INSERT INTO public.competition SELECT * from sqlite39.competition;
INSERT INTO public.competition SELECT * from sqlite40.competition;
INSERT INTO public.competition SELECT * from sqlite41.competition;
INSERT INTO public.competition SELECT * from sqlite42.competition;
INSERT INTO public.competition SELECT * from sqlite43.competition;
INSERT INTO public.competition SELECT * from sqlite44.competition;
INSERT INTO public.competition SELECT * from sqlite45.competition;
INSERT INTO public.competition SELECT * from sqlite46.competition;
INSERT INTO public.competition SELECT * from sqlite47.competition;
INSERT INTO public.competition SELECT * from sqlite48.competition;
INSERT INTO public.competition SELECT * from sqlite49.competition;
INSERT INTO public.competition SELECT * from sqlite50.competition;
INSERT INTO public.competition SELECT * from sqlite51.competition;
INSERT INTO public.competition SELECT * from sqlite52.competition;
INSERT INTO public.competition SELECT * from sqlite53.competition;
INSERT INTO public.competition SELECT * from sqlite54.competition;
INSERT INTO public.competition SELECT * from sqlite55.competition;
INSERT INTO public.competition SELECT * from sqlite56.competition;
INSERT INTO public.competition SELECT * from sqlite57.competition;
INSERT INTO public.competition SELECT * from sqlite58.competition;
INSERT INTO public.competition SELECT * from sqlite59.competition;
INSERT INTO public.competition SELECT * from sqlite60.competition;
INSERT INTO public.competition SELECT * from sqlite61.competition;
INSERT INTO public.competition SELECT * from sqlite62.competition;
INSERT INTO public.competition SELECT * from sqlite63.competition;
INSERT INTO public.competition SELECT * from sqlite64.competition;
INSERT INTO public.competition SELECT * from sqlite65.competition;
INSERT INTO public.competition SELECT * from sqlite66.competition;
INSERT INTO public.competition SELECT * from sqlite67.competition;
INSERT INTO public.competition SELECT * from sqlite68.competition;
INSERT INTO public.competition SELECT * from sqlite69.competition;
INSERT INTO public.competition SELECT * from sqlite70.competition;
INSERT INTO public.competition SELECT * from sqlite71.competition;
INSERT INTO public.competition SELECT * from sqlite72.competition;
INSERT INTO public.competition SELECT * from sqlite73.competition;
INSERT INTO public.competition SELECT * from sqlite74.competition;
INSERT INTO public.competition SELECT * from sqlite75.competition;
INSERT INTO public.competition SELECT * from sqlite76.competition;
INSERT INTO public.competition SELECT * from sqlite77.competition;
INSERT INTO public.competition SELECT * from sqlite78.competition;
INSERT INTO public.competition SELECT * from sqlite79.competition;
INSERT INTO public.competition SELECT * from sqlite80.competition;
INSERT INTO public.competition SELECT * from sqlite81.competition;
INSERT INTO public.competition SELECT * from sqlite82.competition;
INSERT INTO public.competition SELECT * from sqlite83.competition;
INSERT INTO public.competition SELECT * from sqlite84.competition;
INSERT INTO public.competition SELECT * from sqlite85.competition;
INSERT INTO public.competition SELECT * from sqlite86.competition;
INSERT INTO public.competition SELECT * from sqlite87.competition;
INSERT INTO public.competition SELECT * from sqlite88.competition;
INSERT INTO public.competition SELECT * from sqlite89.competition;
INSERT INTO public.competition SELECT * from sqlite90.competition;
INSERT INTO public.competition SELECT * from sqlite91.competition;
INSERT INTO public.competition SELECT * from sqlite92.competition;
INSERT INTO public.competition SELECT * from sqlite93.competition;
INSERT INTO public.competition SELECT * from sqlite94.competition;
INSERT INTO public.competition SELECT * from sqlite95.competition;
INSERT INTO public.competition SELECT * from sqlite96.competition;
INSERT INTO public.competition SELECT * from sqlite97.competition;
INSERT INTO public.competition SELECT * from sqlite98.competition;
INSERT INTO public.competition SELECT * from sqlite99.competition;
INSERT INTO public.competition SELECT * from sqlite100.competition;

-- player
INSERT INTO public.player SELECT * from sqlite1.player;
INSERT INTO public.player SELECT * from sqlite2.player;
INSERT INTO public.player SELECT * from sqlite3.player;
INSERT INTO public.player SELECT * from sqlite4.player;
INSERT INTO public.player SELECT * from sqlite5.player;
INSERT INTO public.player SELECT * from sqlite6.player;
INSERT INTO public.player SELECT * from sqlite7.player;
INSERT INTO public.player SELECT * from sqlite8.player;
INSERT INTO public.player SELECT * from sqlite9.player;
INSERT INTO public.player SELECT * from sqlite10.player;
INSERT INTO public.player SELECT * from sqlite11.player;
INSERT INTO public.player SELECT * from sqlite12.player;
INSERT INTO public.player SELECT * from sqlite13.player;
INSERT INTO public.player SELECT * from sqlite14.player;
INSERT INTO public.player SELECT * from sqlite15.player;
INSERT INTO public.player SELECT * from sqlite16.player;
INSERT INTO public.player SELECT * from sqlite17.player;
INSERT INTO public.player SELECT * from sqlite18.player;
INSERT INTO public.player SELECT * from sqlite19.player;
INSERT INTO public.player SELECT * from sqlite20.player;
INSERT INTO public.player SELECT * from sqlite21.player;
INSERT INTO public.player SELECT * from sqlite22.player;
INSERT INTO public.player SELECT * from sqlite23.player;
INSERT INTO public.player SELECT * from sqlite24.player;
INSERT INTO public.player SELECT * from sqlite25.player;
INSERT INTO public.player SELECT * from sqlite26.player;
INSERT INTO public.player SELECT * from sqlite27.player;
INSERT INTO public.player SELECT * from sqlite28.player;
INSERT INTO public.player SELECT * from sqlite29.player;
INSERT INTO public.player SELECT * from sqlite30.player;
INSERT INTO public.player SELECT * from sqlite31.player;
INSERT INTO public.player SELECT * from sqlite32.player;
INSERT INTO public.player SELECT * from sqlite33.player;
INSERT INTO public.player SELECT * from sqlite34.player;
INSERT INTO public.player SELECT * from sqlite35.player;
INSERT INTO public.player SELECT * from sqlite36.player;
INSERT INTO public.player SELECT * from sqlite37.player;
INSERT INTO public.player SELECT * from sqlite38.player;
INSERT INTO public.player SELECT * from sqlite39.player;
INSERT INTO public.player SELECT * from sqlite40.player;
INSERT INTO public.player SELECT * from sqlite41.player;
INSERT INTO public.player SELECT * from sqlite42.player;
INSERT INTO public.player SELECT * from sqlite43.player;
INSERT INTO public.player SELECT * from sqlite44.player;
INSERT INTO public.player SELECT * from sqlite45.player;
INSERT INTO public.player SELECT * from sqlite46.player;
INSERT INTO public.player SELECT * from sqlite47.player;
INSERT INTO public.player SELECT * from sqlite48.player;
INSERT INTO public.player SELECT * from sqlite49.player;
INSERT INTO public.player SELECT * from sqlite50.player;
INSERT INTO public.player SELECT * from sqlite51.player;
INSERT INTO public.player SELECT * from sqlite52.player;
INSERT INTO public.player SELECT * from sqlite53.player;
INSERT INTO public.player SELECT * from sqlite54.player;
INSERT INTO public.player SELECT * from sqlite55.player;
INSERT INTO public.player SELECT * from sqlite56.player;
INSERT INTO public.player SELECT * from sqlite57.player;
INSERT INTO public.player SELECT * from sqlite58.player;
INSERT INTO public.player SELECT * from sqlite59.player;
INSERT INTO public.player SELECT * from sqlite60.player;
INSERT INTO public.player SELECT * from sqlite61.player;
INSERT INTO public.player SELECT * from sqlite62.player;
INSERT INTO public.player SELECT * from sqlite63.player;
INSERT INTO public.player SELECT * from sqlite64.player;
INSERT INTO public.player SELECT * from sqlite65.player;
INSERT INTO public.player SELECT * from sqlite66.player;
INSERT INTO public.player SELECT * from sqlite67.player;
INSERT INTO public.player SELECT * from sqlite68.player;
INSERT INTO public.player SELECT * from sqlite69.player;
INSERT INTO public.player SELECT * from sqlite70.player;
INSERT INTO public.player SELECT * from sqlite71.player;
INSERT INTO public.player SELECT * from sqlite72.player;
INSERT INTO public.player SELECT * from sqlite73.player;
INSERT INTO public.player SELECT * from sqlite74.player;
INSERT INTO public.player SELECT * from sqlite75.player;
INSERT INTO public.player SELECT * from sqlite76.player;
INSERT INTO public.player SELECT * from sqlite77.player;
INSERT INTO public.player SELECT * from sqlite78.player;
INSERT INTO public.player SELECT * from sqlite79.player;
INSERT INTO public.player SELECT * from sqlite80.player;
INSERT INTO public.player SELECT * from sqlite81.player;
INSERT INTO public.player SELECT * from sqlite82.player;
INSERT INTO public.player SELECT * from sqlite83.player;
INSERT INTO public.player SELECT * from sqlite84.player;
INSERT INTO public.player SELECT * from sqlite85.player;
INSERT INTO public.player SELECT * from sqlite86.player;
INSERT INTO public.player SELECT * from sqlite87.player;
INSERT INTO public.player SELECT * from sqlite88.player;
INSERT INTO public.player SELECT * from sqlite89.player;
INSERT INTO public.player SELECT * from sqlite90.player;
INSERT INTO public.player SELECT * from sqlite91.player;
INSERT INTO public.player SELECT * from sqlite92.player;
INSERT INTO public.player SELECT * from sqlite93.player;
INSERT INTO public.player SELECT * from sqlite94.player;
INSERT INTO public.player SELECT * from sqlite95.player;
INSERT INTO public.player SELECT * from sqlite96.player;
INSERT INTO public.player SELECT * from sqlite97.player;
INSERT INTO public.player SELECT * from sqlite98.player;
INSERT INTO public.player SELECT * from sqlite99.player;
INSERT INTO public.player SELECT * from sqlite100.player;

-- player_score
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite1.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite2.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite3.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite4.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite5.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite6.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite7.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite8.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite9.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite10.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite11.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite12.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite13.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite14.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite15.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite16.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite17.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite18.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite19.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite20.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite21.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite22.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite23.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite24.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite25.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite26.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite27.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite28.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite29.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite30.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite31.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite32.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite33.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite34.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite35.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite36.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite37.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite38.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite39.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite40.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite41.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite42.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite43.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite44.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite45.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite46.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite47.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite48.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite49.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite50.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite51.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite52.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite53.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite54.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite55.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite56.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite57.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite58.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite59.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite60.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite61.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite62.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite63.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite64.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite65.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite66.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite67.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite68.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite69.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite70.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite71.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite72.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite73.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite74.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite75.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite76.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite77.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite78.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite79.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite80.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite81.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite82.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite83.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite84.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite85.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite86.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite87.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite88.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite89.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite90.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite91.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite92.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite93.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite94.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite95.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite96.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite97.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite98.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite99.player_score) AS ranking WHERE rank = 1;
INSERT INTO public.player_score SELECT id,tenant_id,player_id,competition_id,score,row_num,created_at,updated_at FROM (SELECT *,rank() OVER (partition by tenant_id,competition_id,player_id ORDER BY row_num DESC) as rank FROM sqlite100.player_score) AS ranking WHERE rank = 1;