-- schema作成
CREATE schema sqlite1;
CREATE schema sqlite2;
CREATE schema sqlite3;
CREATE schema sqlite4;
CREATE schema sqlite5;
CREATE schema sqlite6;
CREATE schema sqlite7;
CREATE schema sqlite8;
CREATE schema sqlite9;
CREATE schema sqlite10;
CREATE schema sqlite11;
CREATE schema sqlite12;
CREATE schema sqlite13;
CREATE schema sqlite14;
CREATE schema sqlite15;
CREATE schema sqlite16;
CREATE schema sqlite17;
CREATE schema sqlite18;
CREATE schema sqlite19;
CREATE schema sqlite20;
CREATE schema sqlite21;
CREATE schema sqlite22;
CREATE schema sqlite23;
CREATE schema sqlite24;
CREATE schema sqlite25;
CREATE schema sqlite26;
CREATE schema sqlite27;
CREATE schema sqlite28;
CREATE schema sqlite29;
CREATE schema sqlite30;
CREATE schema sqlite31;
CREATE schema sqlite32;
CREATE schema sqlite33;
CREATE schema sqlite34;
CREATE schema sqlite35;
CREATE schema sqlite36;
CREATE schema sqlite37;
CREATE schema sqlite38;
CREATE schema sqlite39;
CREATE schema sqlite40;
CREATE schema sqlite41;
CREATE schema sqlite42;
CREATE schema sqlite43;
CREATE schema sqlite44;
CREATE schema sqlite45;
CREATE schema sqlite46;
CREATE schema sqlite47;
CREATE schema sqlite48;
CREATE schema sqlite49;
CREATE schema sqlite50;
CREATE schema sqlite51;
CREATE schema sqlite52;
CREATE schema sqlite53;
CREATE schema sqlite54;
CREATE schema sqlite55;
CREATE schema sqlite56;
CREATE schema sqlite57;
CREATE schema sqlite58;
CREATE schema sqlite59;
CREATE schema sqlite60;
CREATE schema sqlite61;
CREATE schema sqlite62;
CREATE schema sqlite63;
CREATE schema sqlite64;
CREATE schema sqlite65;
CREATE schema sqlite66;
CREATE schema sqlite67;
CREATE schema sqlite68;
CREATE schema sqlite69;
CREATE schema sqlite70;
CREATE schema sqlite71;
CREATE schema sqlite72;
CREATE schema sqlite73;
CREATE schema sqlite74;
CREATE schema sqlite75;
CREATE schema sqlite76;
CREATE schema sqlite77;
CREATE schema sqlite78;
CREATE schema sqlite79;
CREATE schema sqlite80;
CREATE schema sqlite81;
CREATE schema sqlite82;
CREATE schema sqlite83;
CREATE schema sqlite84;
CREATE schema sqlite85;
CREATE schema sqlite86;
CREATE schema sqlite87;
CREATE schema sqlite88;
CREATE schema sqlite89;
CREATE schema sqlite90;
CREATE schema sqlite91;
CREATE schema sqlite92;
CREATE schema sqlite93;
CREATE schema sqlite94;
CREATE schema sqlite95;
CREATE schema sqlite96;
CREATE schema sqlite97;
CREATE schema sqlite98;
CREATE schema sqlite99;
CREATE schema sqlite100;

-- SQLite接続
CREATE SERVER sqlite_server1 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/1.db');
CREATE SERVER sqlite_server2 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/2.db');
CREATE SERVER sqlite_server3 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/3.db');
CREATE SERVER sqlite_server4 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/4.db');
CREATE SERVER sqlite_server5 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/5.db');
CREATE SERVER sqlite_server6 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/6.db');
CREATE SERVER sqlite_server7 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/7.db');
CREATE SERVER sqlite_server8 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/8.db');
CREATE SERVER sqlite_server9 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/9.db');
CREATE SERVER sqlite_server10 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/10.db');
CREATE SERVER sqlite_server11 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/11.db');
CREATE SERVER sqlite_server12 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/12.db');
CREATE SERVER sqlite_server13 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/13.db');
CREATE SERVER sqlite_server14 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/14.db');
CREATE SERVER sqlite_server15 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/15.db');
CREATE SERVER sqlite_server16 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/16.db');
CREATE SERVER sqlite_server17 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/17.db');
CREATE SERVER sqlite_server18 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/18.db');
CREATE SERVER sqlite_server19 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/19.db');
CREATE SERVER sqlite_server20 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/20.db');
CREATE SERVER sqlite_server21 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/21.db');
CREATE SERVER sqlite_server22 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/22.db');
CREATE SERVER sqlite_server23 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/23.db');
CREATE SERVER sqlite_server24 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/24.db');
CREATE SERVER sqlite_server25 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/25.db');
CREATE SERVER sqlite_server26 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/26.db');
CREATE SERVER sqlite_server27 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/27.db');
CREATE SERVER sqlite_server28 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/28.db');
CREATE SERVER sqlite_server29 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/29.db');
CREATE SERVER sqlite_server30 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/30.db');
CREATE SERVER sqlite_server31 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/31.db');
CREATE SERVER sqlite_server32 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/32.db');
CREATE SERVER sqlite_server33 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/33.db');
CREATE SERVER sqlite_server34 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/34.db');
CREATE SERVER sqlite_server35 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/35.db');
CREATE SERVER sqlite_server36 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/36.db');
CREATE SERVER sqlite_server37 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/37.db');
CREATE SERVER sqlite_server38 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/38.db');
CREATE SERVER sqlite_server39 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/39.db');
CREATE SERVER sqlite_server40 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/40.db');
CREATE SERVER sqlite_server41 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/41.db');
CREATE SERVER sqlite_server42 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/42.db');
CREATE SERVER sqlite_server43 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/43.db');
CREATE SERVER sqlite_server44 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/44.db');
CREATE SERVER sqlite_server45 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/45.db');
CREATE SERVER sqlite_server46 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/46.db');
CREATE SERVER sqlite_server47 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/47.db');
CREATE SERVER sqlite_server48 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/48.db');
CREATE SERVER sqlite_server49 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/49.db');
CREATE SERVER sqlite_server50 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/50.db');
CREATE SERVER sqlite_server51 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/51.db');
CREATE SERVER sqlite_server52 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/52.db');
CREATE SERVER sqlite_server53 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/53.db');
CREATE SERVER sqlite_server54 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/54.db');
CREATE SERVER sqlite_server55 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/55.db');
CREATE SERVER sqlite_server56 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/56.db');
CREATE SERVER sqlite_server57 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/57.db');
CREATE SERVER sqlite_server58 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/58.db');
CREATE SERVER sqlite_server59 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/59.db');
CREATE SERVER sqlite_server60 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/60.db');
CREATE SERVER sqlite_server61 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/61.db');
CREATE SERVER sqlite_server62 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/62.db');
CREATE SERVER sqlite_server63 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/63.db');
CREATE SERVER sqlite_server64 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/64.db');
CREATE SERVER sqlite_server65 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/65.db');
CREATE SERVER sqlite_server66 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/66.db');
CREATE SERVER sqlite_server67 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/67.db');
CREATE SERVER sqlite_server68 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/68.db');
CREATE SERVER sqlite_server69 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/69.db');
CREATE SERVER sqlite_server70 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/70.db');
CREATE SERVER sqlite_server71 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/71.db');
CREATE SERVER sqlite_server72 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/72.db');
CREATE SERVER sqlite_server73 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/73.db');
CREATE SERVER sqlite_server74 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/74.db');
CREATE SERVER sqlite_server75 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/75.db');
CREATE SERVER sqlite_server76 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/76.db');
CREATE SERVER sqlite_server77 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/77.db');
CREATE SERVER sqlite_server78 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/78.db');
CREATE SERVER sqlite_server79 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/79.db');
CREATE SERVER sqlite_server80 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/80.db');
CREATE SERVER sqlite_server81 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/81.db');
CREATE SERVER sqlite_server82 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/82.db');
CREATE SERVER sqlite_server83 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/83.db');
CREATE SERVER sqlite_server84 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/84.db');
CREATE SERVER sqlite_server85 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/85.db');
CREATE SERVER sqlite_server86 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/86.db');
CREATE SERVER sqlite_server87 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/87.db');
CREATE SERVER sqlite_server88 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/88.db');
CREATE SERVER sqlite_server89 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/89.db');
CREATE SERVER sqlite_server90 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/90.db');
CREATE SERVER sqlite_server91 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/91.db');
CREATE SERVER sqlite_server92 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/92.db');
CREATE SERVER sqlite_server93 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/93.db');
CREATE SERVER sqlite_server94 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/94.db');
CREATE SERVER sqlite_server95 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/95.db');
CREATE SERVER sqlite_server96 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/96.db');
CREATE SERVER sqlite_server97 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/97.db');
CREATE SERVER sqlite_server98 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/98.db');
CREATE SERVER sqlite_server99 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/99.db');
CREATE SERVER sqlite_server100 FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/home/isucon/webapp/tenant_db/100.db');

-- add fdw

IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server1 INTO sqlite1;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server2 INTO sqlite2;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server3 INTO sqlite3;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server4 INTO sqlite4;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server5 INTO sqlite5;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server6 INTO sqlite6;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server7 INTO sqlite7;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server8 INTO sqlite8;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server9 INTO sqlite9;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server10 INTO sqlite10;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server11 INTO sqlite11;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server12 INTO sqlite12;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server13 INTO sqlite13;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server14 INTO sqlite14;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server15 INTO sqlite15;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server16 INTO sqlite16;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server17 INTO sqlite17;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server18 INTO sqlite18;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server19 INTO sqlite19;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server20 INTO sqlite20;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server21 INTO sqlite21;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server22 INTO sqlite22;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server23 INTO sqlite23;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server24 INTO sqlite24;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server25 INTO sqlite25;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server26 INTO sqlite26;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server27 INTO sqlite27;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server28 INTO sqlite28;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server29 INTO sqlite29;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server30 INTO sqlite30;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server31 INTO sqlite31;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server32 INTO sqlite32;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server33 INTO sqlite33;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server34 INTO sqlite34;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server35 INTO sqlite35;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server36 INTO sqlite36;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server37 INTO sqlite37;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server38 INTO sqlite38;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server39 INTO sqlite39;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server40 INTO sqlite40;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server41 INTO sqlite41;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server42 INTO sqlite42;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server43 INTO sqlite43;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server44 INTO sqlite44;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server45 INTO sqlite45;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server46 INTO sqlite46;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server47 INTO sqlite47;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server48 INTO sqlite48;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server49 INTO sqlite49;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server50 INTO sqlite50;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server51 INTO sqlite51;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server52 INTO sqlite52;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server53 INTO sqlite53;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server54 INTO sqlite54;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server55 INTO sqlite55;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server56 INTO sqlite56;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server57 INTO sqlite57;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server58 INTO sqlite58;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server59 INTO sqlite59;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server60 INTO sqlite60;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server61 INTO sqlite61;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server62 INTO sqlite62;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server63 INTO sqlite63;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server64 INTO sqlite64;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server65 INTO sqlite65;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server66 INTO sqlite66;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server67 INTO sqlite67;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server68 INTO sqlite68;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server69 INTO sqlite69;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server70 INTO sqlite70;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server71 INTO sqlite71;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server72 INTO sqlite72;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server73 INTO sqlite73;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server74 INTO sqlite74;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server75 INTO sqlite75;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server76 INTO sqlite76;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server77 INTO sqlite77;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server78 INTO sqlite78;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server79 INTO sqlite79;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server80 INTO sqlite80;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server81 INTO sqlite81;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server82 INTO sqlite82;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server83 INTO sqlite83;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server84 INTO sqlite84;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server85 INTO sqlite85;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server86 INTO sqlite86;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server87 INTO sqlite87;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server88 INTO sqlite88;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server89 INTO sqlite89;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server90 INTO sqlite90;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server91 INTO sqlite91;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server92 INTO sqlite92;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server93 INTO sqlite93;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server94 INTO sqlite94;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server95 INTO sqlite95;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server96 INTO sqlite96;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server97 INTO sqlite97;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server98 INTO sqlite98;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server99 INTO sqlite99;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server100 INTO sqlite100;